// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ContinueExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "ContinueExtension.db0e6618-c390-497e-9f8c-a2708ef55438";
        public const string Name = "ContinueExtension";
        public const string Description = @"Code Suggestion use Contiue Ollama";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "dung.nt172500";
        public const string Tags = "";
    }
}
